### ISSUE TITLE
parse_ipv6 implementation is missing

### ISSUE THREAD

**Issue by calavera** [tohojo/xdp-paper#1]
Hi! :wave: 

I was reading the paper and I noticed that in Listing 1 there is a function implementation missing. In line 55 of that code, there is a call to `ipproto = parse_ipv6(data, nh_off, data_end)`, but that function is never defined before that call.

**Comment by tohojo** [comment]
David Calavera <notifications@github.com> writes:

> Hi! :wave: 
>
> I was reading the paper and I noticed that in Listing 1 there is a
> function implementation missing. In line 55 of that code, there is a
> call to `ipproto = parse_ipv6(data, nh_off, data_end)`, but that
> function is never defined before that call.

Yeah, the version in the paper omits a few details in order to fit on
the page. The full example is distributed with the kernel source code.
See
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/samples/bpf/xdp2_kern.c

**Comment by calavera** [comment]
that makes a lot of sense, thanks. Maybe, you should consider adding that reference to the paper, I'm not sure if it's there.

**Comment by tohojo** [comment]
Well, it sort of says so in the figure text? :)
