### ISSUE TITLE
ethtool_stats.pl and napi_monitor

### ISSUE THREAD

**Issue by ngsrinivas** [tohojo/xdp-paper#3]
Hi xdp team,

There are references to an ethtool output processing script `ethtool_stats.pl` in several of the benchmark org files. I couldn't locate the file in this repository or the kernel source. 

Also there is a reference to a tool `napi_monitor` to look at NAPI statistics.

Kindly provide a reference to these tools? Sorry if I missed something basic. 

Thanks!
Srinivas

**Comment by tohojo** [comment]
Srinivas Narayana <notifications@github.com> writes:

> Hi xdp team,
>
> There are references to an ethtool output processing script
> `ethtool_stats.pl` in several of the benchmark org files. I couldn't
> locate the file in this repository or the kernel source.

https://github.com/netoptimizer/network-testing/blob/master/bin/ethtool_stats.pl

> Also there is a reference to a tool `napi_monitor` to look at NAPI
> statistics.

napi_monitor is the one in this directory, I think (@netoptimizer can
confirm):

https://github.com/netoptimizer/prototype-kernel/tree/master/kernel/samples/bpf

**Comment by ngsrinivas** [comment]
Thank you so much for the prompt and helpful reply.

Srinivas

**Comment by tohojo** [comment]
Srinivas Narayana <notifications@github.com> writes:

> Thank you so much for the prompt and helpful reply.

You're welcome :)

**Comment by netoptimizer** [comment]
I confirm these are the tools
